### ISSUE TITLE
CommandLine#forceExecuteで割り込み例外が発生する

### ISSUE THREAD

**Issue by T45K** [T45K/PART#25]
ログ

```
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
        at com.github.kusumotolab.sdl4j.util.CommandLine.execute(CommandLine.java:37)
        at com.github.kusumotolab.sdl4j.util.CommandLine.forceExecute(CommandLine.java:18)
        at io.github.t45k.part.mining.git.GitLogCommand.execute(GitLogCommand.kt:12)
```

Process#waitFor で発生
例外は`try-catch`で掴んでいるはず
Nativeメソッドのせいかも

**Comment by T45K** [comment]
原因は他のプロセスでのException(ex. IllegalArgumentException)
これが原因で親プロセスが各子プロセスを止める -> 割り込み例外っぽい

**Comment by T45K** [comment]
原因がはっきりしているので解決で
