### ISSUE TITLE
prettyPrintLogの返り値が[[]]になって配列外アクセスエラーになる

### ISSUE THREAD

**Issue by T45K** [T45K/PART#31]
ref #29 

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at io.github.t45k.part.mining.git.GitLogCommand.parseCommandLineResult(GitLogCommand.kt:21)
```

**Comment by T45K** [comment]
再現しない

**Comment by T45K** [comment]
そもそも`rawLog`が空になることがおかしい
